# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
# https://github.com/home-assistant/docker-base
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:latest"
  amd64: "ghcr.io/home-assistant/amd64-base-python:latest"
  armhf: "ghcr.io/home-assistant/armhf-base-python:latest"
  armv7: "ghcr.io/home-assistant/armv7-base-python:latest"
  i386: "ghcr.io/home-assistant/i386-base-python:latest"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: RESOL VBus to HomA MQTT"
  org.opencontainers.image.description: "RESOL VBus to HomA MQTT add-on."
  org.opencontainers.image.source: "https://github.com/hass-hmueller01/addon-resol-vbus-homa"
  org.opencontainers.image.licenses: "MIT License"
squash: true
