# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
# https://github.com/home-assistant/docker-base
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:latest"
  amd64: "ghcr.io/home-assistant/amd64-base-python:latest"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: HomA MQTT min/max saver"
  org.opencontainers.image.description: "HomA MQTT min/max saver add-on."
  org.opencontainers.image.source: "https://github.com/hass-hmueller01/addon-min-max-saver-homa"
  org.opencontainers.image.licenses: "MIT License"
