# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:latest"
  amd64: "ghcr.io/home-assistant/amd64-base:latest"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: SML to HomA MQTT"
  org.opencontainers.image.description: "SML to HomA MQTT add-on."
  org.opencontainers.image.source: "https://github.com/hass-hmueller01/addon-sml-homa"
  org.opencontainers.image.licenses: "MIT License"
