# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:bookworm"
  amd64: "ghcr.io/home-assistant/amd64-base-debian:bookworm"
  armhf: "ghcr.io/home-assistant/armhf-base-debian:bookworm"
  armv7: "ghcr.io/home-assistant/armv7-base-debian:bookworm"
  i386: "ghcr.io/home-assistant/i386-base-debian:bookworm"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: OpenV vcontrold to HomA MQTT"
  org.opencontainers.image.description: "OpenV vcontrold to HomA MQTT add-on."
  org.opencontainers.image.source: "https://github.com/hass-hmueller01/addon-openv-homA"
  org.opencontainers.image.licenses: "MIT License"
args:
  TEMPIO_VERSION: "2021.09.0"
squash: true
